// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: unfollow.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const deleteFeedFollowByUserAndURL = `-- name: DeleteFeedFollowByUserAndURL :exec
DELETE FROM feed_follows
WHERE feed_follows.user_id = $1
    AND feed_follows.feed_id = (
        SELECT id FROM feeds WHERE url = $2
    )
`

type DeleteFeedFollowByUserAndURLParams struct {
	UserID uuid.UUID `json:"user_id"`
	Url    string    `json:"url"`
}

func (q *Queries) DeleteFeedFollowByUserAndURL(ctx context.Context, arg DeleteFeedFollowByUserAndURLParams) error {
	_, err := q.db.ExecContext(ctx, deleteFeedFollowByUserAndURL, arg.UserID, arg.Url)
	return err
}
